language: python
python:
  - "2.7"

before_install:
  - pwd
  - ls
  # it's strange why need this step since it's in the package directory already
  # - export PYTHONPATH=${PWD}:${PYTHONPATH}

install:
  - pwd
  - pip install -U pip setuptools
  - python setup.py develop
  # - pip install -r requirements.txt

script:
  - py.test -s --cov=rsempipeline --cov-report=html tests/

after_success:
  - coveralls

notifications:
  email: false