language: python
python:
  - "2.7"

install:
  - "pip install ."
  - "pip install -r requirements.txt"
  - "pip install git+https://github.com/bcgsc/rsempipeline.git#egg=rsempipeline"

script:
  - "py.test --cov=rsempipeline --cov-report=html tests/"
