language: python
python:
  - "2.7"

before_install:
  - pwd
  - ls
  - export PYTHONPATH=${PWD}:${PYTHONPATH}

install:
  - pwd
  - pip install -r requirements.txt

script:
  - py.test -s --cov=rsempipeline --cov-report=html tests/
