# Configurations that change when in different hosts should be put here, those
# that don't change (e.g. logging configuration) should be put in settings.py

SPECIES_INFO:
  Homo sapiens:
    short_name: human
    index: /projects/btl2/batch.2013.05.22/rsem/hg19/hg19_ensembl_72
  Mus musculus:
    short_name: mouse
    index: /projects/btl2/batch.2013.05.22/rsem/mm10/mm10_ensembl_72
  Rattus norvegicus:
    short_name: rat
    index: /projects/btl2/batch.2013.05.22/rsem/rn5/rn5_ensembl_72

